name: paguyuban
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.5.0+5

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  google_fonts: ^6.2.1
  http: ^1.2.1
  animated_splash_screen: ^1.3.0
  carousel_slider: ^5.0.0
  auto_size_text: ^3.0.0
  webview_flutter: ^4.8.0
  animate_do: ^3.3.4
  salomon_bottom_bar: ^3.3.2
  intl: ^0.19.0
  flutter_map: any
  flutter_map_marker_cluster: any 
  latlong2: ^0.9.1
  bottom_sheet: ^4.0.4
  url_launcher: ^6.3.0
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.2.3
  audioplayers: ^6.0.0
  cached_network_image: ^3.3.1
  readmore: ^3.0.0
  pretty_qr_code: ^3.3.0
  screenshot: ^3.0.0
  path_provider: ^2.1.4
  share_plus: ^10.0.2
  image_picker: ^1.0.0
  flutter_image_compress: ^2.3.0
  image_cropper: ^8.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
    
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/buku_infografis/
    - assets/logo/
    - assets/coffee_mart/
